server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SeniorLink?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

  servlet:
    multipart:
      location: C:/Users/user/Desktop/SumiSong/전공 과목/캡스톤/seniorlink/senior-link/src/main/resources/static/profile
